export enum ErrorCode {
    // General
    BAD_REQUEST = "BAD_REQUEST",
    UNAUTHORIZED = "UNAUTHORIZED",
    FORBIDDEN = "FORBIDDEN",
    NOT_FOUND = "NOT_FOUND",
    CONFLICT = "CONFLICT",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    VALIDATION_FAILED = "VALIDATION_FAILED",

    // Coupons
    COUPON_NOT_FOUND = "COUPON_NOT_FOUND",
    COUPON_EXPIRED = "COUPON_EXPIRED",
    COUPON_USAGE_LIMIT = "COUPON_USAGE_LIMIT",
    COUPON_INACTIVE = "COUPON_INACTIVE",
    COUPON_MIN_AMOUNT = "COUPON_MIN_AMOUNT",
    COUPON_CURRENCY_MISMATCH = "COUPON_CURRENCY_MISMATCH",
    COUPON_INVALID_PLAN = "COUPON_INVALID_PLAN",
    COUPON_ALREADY_USED = "COUPON_ALREADY_USED",

    // Subscriptions
    SUBSCRIPTION_NOT_FOUND = "SUBSCRIPTION_NOT_FOUND",
    SUBSCRIPTION_INACTIVE = "SUBSCRIPTION_INACTIVE",
    SUBSCRIPTION_CANCELED = "SUBSCRIPTION_CANCELED",
    SUBSCRIPTION_NOT_CANCELLABLE = "SUBSCRIPTION_NOT_CANCELLABLE",
    SUBSCRIPTION_ALREADY_ACTIVE = "SUBSCRIPTION_ALREADY_ACTIVE",

    // Authentication / Tokens
    INVALID_CHECKOUT_TOKEN = "INVALID_CHECKOUT_TOKEN",
    INVALID_PORTAL_TOKEN = "INVALID_PORTAL_TOKEN",
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
    ACCOUNT_EXISTS = "ACCOUNT_EXISTS",

    // Entities
    SUBSCRIBER_NOT_FOUND = "SUBSCRIBER_NOT_FOUND",
    INVOICE_NOT_FOUND = "INVOICE_NOT_FOUND",
    WEBHOOK_ENDPOINT_NOT_FOUND = "WEBHOOK_ENDPOINT_NOT_FOUND",
    API_KEY_NOT_FOUND = "API_KEY_NOT_FOUND",
    SQUAD_NOT_FOUND = "SQUAD_NOT_FOUND",
}
