services:
  anybill:
    image: ghcr.io/dortanes/anybill:latest
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - PROVIDERS=/providers
    volumes:
      - anybill-data:/data
      - ./providers:/providers:ro

volumes:
  anybill-data:
